version: 2.1
 
orbs:
  android: circleci/android@2.4.0
 
jobs:
  build:
    docker:
      - image: cimg/android:2024.01
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: build_reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Coverage Test
          command: ./gradlew koverReport
      - store_test_results:
          path: app/build/test-results
          destination: test_results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: apks
      - store_artifacts:  
          path: app/build/reports/kover
          destination: kover_reports
      - store_artifacts:  
          path: core/build/reports/kover
          destination: kover_reports
      - store_artifacts:  
          path: favorite/build/reports/kover
          destination: kover_reports
